FROM ubuntu:20.04 AS builder
WORKDIR /app
COPY . /app
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get install --no-install-recommends --no-install-suggests -y gnupg2 ca-certificates git build-essential libopencv-dev python3 pip libgl1-mesa-glx vim
RUN rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir --upgrade -r requirements.txt
RUN cd app/darknet && make

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]